name: CI/CD flask container app

on:
  push:
    branches: [ master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    # Add QEMU setup to test the support for more platforms (this is optional but recommended)
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Build Docker image
      run: |
        docker build -t flask-predict .
    
    - name: Run the docker container
      run: |
        docker run -d -p 5001:5001 flask-predict
    
    - name: Wait for Flask app to start
      run: sleep 5
    
    - name: Test the flask application "GET" endpoints
      run: |
        curl --fail http://localhost:5001 || exit 1
        curl --fail http://localhost:5001/example || exit 1
        curl --fail http://localhost:5001/metadata || exit 1
    
    - name: Stop the docker container and remove it
      run: |
        docker stop flask-predict && docker rm flask-predict
